In [1]:
import editdistance
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
import numpy as np


In [2]:
ed_array =np.zeros((11,11))
path_to_trimmed = "sequences_trimmed.fasta"
path = "sequences_filtered_10.fasta"
i = -1
for record in SeqIO.parse(path, "fasta"):
    i+=1
    if record.id != "hCoV-19/USA/CA-HLX-STM-5GZTN7FJC/2021":
        j=-1
        for record2 in SeqIO.parse(path, "fasta"):
            if record2.id != "hCoV-19/USA/CA-HLX-STM-5GZTN7FJC/2021":
                j+=1
                ed =editdistance.eval(record.seq, record2.seq)
                ed_array[i][j] = ed

In [3]:
print(ed_array)

[[   0.  290.  554.  294.  429.  725.  341. 1153.  552.  352.    0.]
 [ 290.    0.  307.   30.  187.  490.   84.  896.  321.  109.    0.]
 [ 554.  307.    0.  324.  481.  778.  378. 1190.  615.  403.    0.]
 [ 294.   30.  324.    0.  197.  470.   94.  890.  308.   99.    0.]
 [ 429.  187.  481.  197.    0.  431.  115.  899.  179.  184.    0.]
 [ 725.  490.  778.  470.  431.    0.  418. 1186.  354.  447.    0.]
 [ 341.   84.  378.   94.  115.  418.    0.  818.  249.  119.    0.]
 [1153.  896. 1190.  890.  899. 1186.  818.    0. 1014.  905.    0.]
 [ 552.  321.  615.  308.  179.  354.  249. 1014.    0.  311.    0.]
 [ 352.  109.  403.   99.  184.  447.  119.  905.  311.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]]


In [6]:
from collections import Counter 
ba1 = next(SeqIO.parse("../sequences/BA.1_EPI_ISL_10223811.fasta", "fasta"))
ba2 = next(SeqIO.parse("../sequences/BA.2_EPI_ISL_10268413.fasta", "fasta"))
ba2ref = next(SeqIO.parse("../sequences/BA.2/1646230814919.sequences.fasta", "fasta"))
ed_dist_to_bas = np.zeros((2,10))

path_to_trimmed = "sequences_trimmed.fasta"
path = "sequences_filtered_10.fasta"

indx_seqid = {
"hCoV-19/USA/TN-ASC-210578418/2021": 0,	
"hCoV-19/USA/TN-ASC-210594362/2021": 1,	
"hCoV-19/USA/TN-ASC-210594334/2021": 2,	
"hCoV-19/USA/TN-ASC-210580074/2021": 3,	
"hCoV-19/USA/CA-LACPHL-AF06940/2021": 4,	
"hCoV-19/USA/IL-IDPH-RAN-SV-002604/2021": 5,	
"hCoV-19/USA/ID-IBL-779207/2021": 6,	
"hCoV-19/USA/ID-IBL-779196/2021": 7,
"hCoV-19/USA/MD-CDC-LC0437785/2021": 8,
"hCoV-19/USA/NC-CLT-CORVASEQ-004208/2021":9
}

ba2refed = np.zeros(10)
for record in SeqIO.parse(path, "fasta"):
    if record.id != "hCoV-19/USA/CA-HLX-STM-5GZTN7FJC/2021":
        if None != Counter(record.seq).get("N"):
            N = Counter(record.seq).get("N")
        else:
            N = 0
        edba1 = editdistance.eval(record.seq,ba1.seq) 
        edba2 = editdistance.eval(record.seq, ba2.seq) 
        ed_dist_to_bas[0][indx_seqid.get(record.id)] = edba1
        ed_dist_to_bas[1][indx_seqid.get(record.id)] = edba2
        # ba2refed[indx_seqid.get(record.id)] = editdistance.eval(record.seq, ba2ref.seq)

# print(ba2refed)        
print(ed_dist_to_bas)

[[307.  39. 333.  51. 154. 457.  57. 862. 288.  94.]
 [394. 164. 455. 162. 180. 448. 122. 922. 290. 154.]]


In [7]:
from collections import Counter 
ba1 = next(SeqIO.parse("../sequences/BA.1_EPI_ISL_10223811.fasta", "fasta"))
ba2 = next(SeqIO.parse("../sequences/BA.2_EPI_ISL_10268413.fasta", "fasta"))
ba2ref = next(SeqIO.parse("../sequences/BA.2/1646230814919.sequences.fasta", "fasta"))
# print(ba1.id)
edba1 = editdistance.eval(ba1.seq, ba2ref)
edba2 = editdistance.eval(ba2.seq, ba2ref)

print(edba1, edba2)


198 132
